### PR TITLE
Host opt out form

### PR DESCRIPTION
**Pull request by wheresrhys**
@matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
some whitespace issues in the `Makefile` preventing me from running this locally

**Comment by matthew-andrews** [comment]
Do you think we could get some `test-urls` hitting this?

**Comment by wheresrhys** [comment]
yep. Also nightwatch

**Comment by wheresrhys** [comment]
ES6

**Comment by matthew-andrews** [comment]
you could steal a nightwatch test from here:-
https://github.com/Financial-Times/next-health/blob/master/nightwatch/tests/opt-out.js

**Comment by wheresrhys** [comment]
Should we merge https://github.com/Financial-Times/next-user-feedback with this app too? It's an integral part of the opt-out journey and if we e.g. want to do some iteration on how we collect user feedback elsewhere in next we don't really want to be treading on opt-out eggshells

**Comment by matthew-andrews** [comment]
good idea

**Comment by wheresrhys** [comment]
I'll leave that for another PR tomorrow as this is already a monster. I'll add test-urls here... then :+1:?

**Comment by matthew-andrews** [comment]
yep

**Comment by matthew-andrews** [comment]
does opt in out need adding to config vase?

**Comment by matthew-andrews** [comment]
can you wait until tomorrow before merging… want to test this properly in a more awake state

**Comment by wheresrhys** [comment]
sure. I don't relish keeping an eye on it after rolling out late afternoon either

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
