### PR TITLE
fire ijento tracking and deny entry to the googlebot

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
oh mann

**Comment by aintgoin2goa** [comment]
^^ that's good, right?

**Comment by matthew-andrews** [comment]
hmm slightly worried about a redirect loop

**Comment by matthew-andrews** [comment]
might the google bot get sent back to m dot and then sent back through to next again?

**Comment by matthew-andrews** [comment]
i think we need this here but also probably need somehting in the varnish to stop it sending us the google bot

**Comment by aintgoin2goa** [comment]
good point - will add that in

**Comment by aintgoin2goa** [comment]
Thankfully the labs varnish as a IsABot header  we should copy that for ours....

**Comment by matthew-andrews** [comment]
oh wow amazing

**Comment by aintgoin2goa** [comment]
If you have concerns about the googlebot bit I could just remove it - need to get the ijento bit up asap...

**Comment by matthew-andrews** [comment]
nah this is fien :+1:

**Comment by matthew-andrews** [comment]
just one of us should do some google bot testing tody/tomorrow

**Pull request merged**
