### PR TITLE
importing user data from legacy FT features, starting with portfolio

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by keirog** [comment]
Isn't this more of an export?

**Comment by wheresrhys** [comment]
export then import. But all the exporting from FT stuff is done in user prefs within the `/import` endpoint (which I think is the correct name over there as it's importing into itself)

**Comment by keirog** [comment]
I would just call it exportData to make it clearer that nothing else is happening with it, within this app. But no big deal; :+1: either way

**Comment by commuterjoy** [comment]
Why is this in opt-in?

**Comment by wheresrhys** [comment]
Most of the logic is in user prefs - this just calls the user prefs endpoint.

I'm not really sure where to put it longer term as opt-in doesn't cover users who have already opted in, but I don't know where I'd put it for them. Easiest is probably just to get a list of uuids and do them all as a job

**Comment by aintgoin2goa** [comment]
Is this still needed?

**Comment by matthew-andrews** [comment]
even if it is needed as matt c implied…… doesn't feel like the right place

**Comment by wheresrhys** [comment]
We're waiting on the new myft api which'll enable doing nicer things around the UI for this.

Why does it not feel like the right place? 'Opt me in' and 'Import my old stuff' feel like complementary tasks

**Pull request closed without merging**
